service: jandi-band-py-scraper
frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.12
  region: ap-northeast-2
  stage: dev
  timeout: 10
  memorySize: 512
  environment:
    LOG_LEVEL: INFO

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true # lxml과 같은 C-extension 종속성을 위해 필요
    strip: false  # 디버깅을 위해 심볼 정보 유지
    slim: true

functions:
  api:
    handler: app.handler # app.py 파일의 handler 객체를 지정
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
      - httpApi:
          path: /
          method: ANY
    # CORS 설정을 API Gateway에서도 처리
    environment:
      PYTHONPATH: ${self:provider.environment.PYTHONPATH, '/var/runtime:/var/task'}

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'
    - '!.serverless/**'
    - '!.idea/**'
    - '!__pycache__/**'
    - '!*.pyc'
    - '!.git/**'
    - '!tests/**'
